"use client";

import { useMemo, useState } from "react";

type AgentKey = "acquisition" | "growth" | "persona" | "retention";
type Agent = { index: string; eyebrow: string; title: string; short: string; description: string; questions: string[]; inputs: string[]; outputs: string[]; accent: string };

const agents: Record<AgentKey, Agent> = {
  acquisition: { index: "01", eyebrow: "Acquire intelligence", title: "获客分析 Agent", short: "找到真正带来收入的渠道", description: "把广告、内容、搜索、社交媒体、AI 搜索与 CRM 数据串成一条可验证的归因链路。", questions: ["客户从哪里来？", "哪些内容和关键词有效？", "哪些客户最可能成交？"], inputs: ["广告与官网数据", "搜索关键词", "AI 搜索曝光", "询盘、报价与成交"], outputs: ["渠道质量排名", "高价值关键词", "内容到 GMV 归因", "下一阶段预算建议"], accent: "#ff7a45" },
  growth: { index: "02", eyebrow: "Growth diagnostics", title: "增长分析 Agent", short: "解释业务为什么增长或下降", description: "不止报出销售额变化，更进一步拆解产品、市场、人群、渠道和竞品带来的真实影响。", questions: ["销售额为什么变化？", "增长是否可持续？", "转化率在哪个环节下降？"], inputs: ["流量与点击", "加购与订单", "客单价与复购", "竞品与 AI 流量"], outputs: ["增长驱动拆解", "异常根因定位", "竞争替代预警", "增长动作优先级"], accent: "#6d6bff" },
  persona: { index: "03", eyebrow: "Persona intelligence", title: "用户画像 Agent", short: "理解谁在购买、为何购买", description: "从年龄与地区之外，深入到使用场景、购买动机、价格敏感度、反对理由和竞品偏好。", questions: ["企业究竟服务哪些人？", "不同人群的购买理由是什么？", "谁最容易转化或流失？"], inputs: ["订单与评价", "内容互动", "搜索与问答", "竞品选择与人群标签"], outputs: ["动态 Persona", "需求与痛点地图", "分层 Prompt", "Listing 与话术模板"], accent: "#12b886" },
  retention: { index: "04", eyebrow: "Lifecycle operations", title: "用户运营 Agent", short: "让一次成交变成长期增长", description: "连接 CRM、用户状态与触达渠道，预测下一步行为并自动安排教育、召回、复购和转介绍动作。", questions: ["如何让潜客持续转化？", "如何提升复购率？", "如何召回沉默客户？"], inputs: ["用户生命周期", "购买与使用行为", "客户标签", "触达与运营结果"], outputs: ["分层运营策略", "自动触达动作", "复购与召回方案", "标签自动更新"], accent: "#e3a72f" },
};

const flowNodes = [
  { label: "获客数据", sub: "广告 · 内容 · AI 搜索", x: 16, y: 23 },
  { label: "用户洞察", sub: "Persona · 意图 · 阶段", x: 84, y: 23 },
  { label: "增长诊断", sub: "原因 · 机会 · 优先级", x: 84, y: 77 },
  { label: "运营动作", sub: "触达 · 转化 · 复购", x: 16, y: 77 },
];

export default function Home() {
  const [active, setActive] = useState<AgentKey>("acquisition");
  const agent = agents[active];
  const activeIndex = Object.keys(agents).indexOf(active);
  const progress = useMemo(() => `${((activeIndex + 1) / 4) * 100}%`, [activeIndex]);
  return (
    <main>
      <nav className="nav shell"><a className="brand" href="#top"><span className="brand-mark">S</span><span>Sun-Shine<span className="brand-dot">.ai</span></span></a><div className="nav-links"><a href="#system">系统能力</a><a href="#agents">四大 Agent</a><a href="#method">增长闭环</a></div><a className="nav-cta" href="#contact">预约演示 <span>↗</span></a></nav>
      <section id="top" className="hero shell"><div className="hero-copy"><div className="kicker"><span className="live-dot" /> CUSTOMER &amp; GROWTH INTELLIGENCE</div><h1>让每一次增长，<br /><em>都有证据。</em></h1><p className="hero-lead">从 AI 搜索曝光到真实 GMV，Sun-Shine.ai 把客户、内容、渠道和成交连接成一套可执行的增长系统。</p><div className="hero-actions"><a className="primary-btn" href="#agents">探索四大 Agent <span>↓</span></a><a className="text-btn" href="#method">查看增长闭环 <span>↗</span></a></div><div className="hero-proof"><div><strong>01</strong><span>归因链路</span></div><div><strong>04</strong><span>增长 Agent</span></div><div><strong>∞</strong><span>持续学习</span></div></div></div><div className="hero-visual" aria-label="客户与增长智能系统动态示意图"><div className="orbital orbital-a" /><div className="orbital orbital-b" /><svg viewBox="0 0 520 520" role="img"><defs><linearGradient id="heroGlow" x1="0" x2="1"><stop offset="0" stopColor="#ff7a45" /><stop offset="1" stopColor="#6d6bff" /></linearGradient></defs><circle cx="260" cy="260" r="178" fill="none" stroke="#24243a" strokeWidth="1" strokeDasharray="4 12" /><circle cx="260" cy="260" r="115" fill="none" stroke="#24243a" strokeWidth="1" /><path className="orbit-path" d="M260 82 A178 178 0 1 1 259.9 82" fill="none" stroke="url(#heroGlow)" strokeWidth="2" strokeDasharray="14 18" /><circle cx="260" cy="260" r="92" fill="#191827" stroke="#3a3954" /><circle cx="260" cy="260" r="70" fill="#222039" stroke="#ff7a45" strokeOpacity=".45" /><text x="260" y="252" textAnchor="middle" className="svg-label main">SUN-SHINE</text><text x="260" y="274" textAnchor="middle" className="svg-label sub">GROWTH OS</text><g className="satellite s1"><circle cx="260" cy="82" r="9" fill="#ff7a45" /><text x="260" y="58" textAnchor="middle" className="svg-label node">ACQUIRE</text></g><g className="satellite s2"><circle cx="438" cy="260" r="9" fill="#6d6bff" /><text x="470" y="264" textAnchor="middle" className="svg-label node">DIAGNOSE</text></g><g className="satellite s3"><circle cx="260" cy="438" r="9" fill="#12b886" /><text x="260" y="474" textAnchor="middle" className="svg-label node">ACTIVATE</text></g><g className="satellite s4"><circle cx="82" cy="260" r="9" fill="#e3a72f" /><text x="47" y="264" textAnchor="middle" className="svg-label node">RETAIN</text></g></svg><div className="visual-caption"><span className="pulse" /> Live system map <span>·</span> Data to decision</div></div></section>
      <section id="system" className="band dark-band"><div className="shell band-inner"><div><span className="section-label">01 / THE SYSTEM</span><h2>不是报表工具，<br /><span>是增长诊断系统。</span></h2></div><p>传统工具告诉你发生了什么。Sun-Shine.ai 继续追问：为什么发生？下一步应该做什么？并把建议连接到实际运营动作。</p></div></section>
      <section id="agents" className="agents-section shell"><div className="section-head"><div><span className="section-label">02 / FOUR AGENTS</span><h2>一套系统，四种<br /><span>增长视角。</span></h2></div><p>点击切换 Agent，查看它如何把业务问题转化为数据洞察与行动建议。</p></div><div className="agent-layout"><div className="agent-tabs">{(Object.keys(agents) as AgentKey[]).map((key) => <button key={key} className={`agent-tab ${active === key ? "active" : ""}`} onClick={() => setActive(key)} style={{ "--agent-accent": agents[key].accent } as React.CSSProperties}><span className="tab-index">{agents[key].index}</span><span><strong>{agents[key].title}</strong><small>{agents[key].short}</small></span><span className="tab-arrow">↗</span></button>)}</div><div className="agent-detail" style={{ "--agent-accent": agent.accent } as React.CSSProperties}><div className="detail-top"><span className="detail-eyebrow">{agent.eyebrow}</span><span className="detail-count">{agent.index} / 04</span></div><h3>{agent.title}</h3><p className="detail-description">{agent.description}</p><div className="detail-columns"><div><span className="mini-label">它要回答</span>{agent.questions.map((q) => <p className="question" key={q}><span>+</span>{q}</p>)}</div><div><span className="mini-label">连接数据</span><div className="chips">{agent.inputs.map((input) => <span className="chip" key={input}>{input}</span>)}</div></div></div><div className="output-row"><span className="mini-label">输出结果</span><div className="output-list">{agent.outputs.map((output) => <span key={output}><i />{output}</span>)}</div></div><div className="detail-progress"><span style={{ width: progress, background: agent.accent }} /><b style={{ color: agent.accent }}>{agent.index}</b></div></div></div></section>
      <section id="method" className="loop-section"><div className="shell"><div className="section-head light"><div><span className="section-label">03 / THE FLYWHEEL</span><h2>从数据到决策，<br /><span>形成增长闭环。</span></h2></div><p>每一个 Agent 都不是终点，而是下一次学习的起点。系统会把行动结果写回数据层，持续提高判断质量。</p></div><div className="flow-card"><svg className="flow-svg" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M16 23 C43 7 67 7 84 23 C100 40 100 60 84 77 C67 93 43 93 16 77 C0 60 0 40 16 23Z" fill="none" stroke="#37364e" strokeWidth=".35" strokeDasharray="1.3 2" /><path className="flow-dash" d="M16 23 C43 7 67 7 84 23 C100 40 100 60 84 77 C67 93 43 93 16 77 C0 60 0 40 16 23Z" fill="none" stroke="#ff7a45" strokeWidth=".55" strokeDasharray="3 5" /></svg>{flowNodes.map((node, i) => <div key={node.label} className={`flow-node node-${i}`}><span className="flow-number">0{i + 1}</span><strong>{node.label}</strong><small>{node.sub}</small></div>)}<div className="flow-center"><span>Sun-Shine</span><b>Growth Loop</b></div></div></div></section>
      <section id="contact" className="contact shell"><div><span className="section-label">04 / NEXT MOVE</span><h2>把增长从“感觉”，<br /><em>变成可计算的动作。</em></h2></div><div className="contact-side"><p>适用于出海品牌、独立站、电商团队与正在建设 AI Commerce 能力的企业。</p><a className="primary-btn dark" href="mailto:hello@sun-shine.ai">预约一次增长诊断 <span>↗</span></a></div></section>
      <footer className="footer shell"><a className="brand" href="#top"><span className="brand-mark">S</span><span>Sun-Shine<span className="brand-dot">.ai</span></span></a><span>Customer &amp; Growth Intelligence</span><span>© 2026 Sun-Shine.ai</span></footer>
    </main>
  );
}
