const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const sandbox = { window: {} };
vm.runInNewContext(fs.readFileSync('sunshine-content.js', 'utf8'), sandbox);
const existing = sandbox.window.SUNSHINE_CONTENT.languages;
const extra = require('../site-content.js');
const out = 'public';
fs.mkdirSync(out, { recursive: true });
for (const folder of ['img', 'video']) fs.cpSync(folder, path.join(out, folder), { recursive: true });
for (const file of ['sun-shine-logo.png', 'sunshine-signal-flow.svg']) fs.copyFileSync(file, path.join(out, file));
fs.copyFileSync('src/site.css', path.join(out, 'site.css'));
fs.copyFileSync('site.js', path.join(out, 'site.js'));
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;'}[c]));
const routes = ['about', 'products', 'cases', 'blog', 'faq', 'contact'];
const labels = {zh:['关于 SunShine','产品','成功案例','博客','FAQ','联系我们'],en:['About SunShine','Products','Case studies','Blog','FAQ','Contact']};
const cards = items => items.map(([title,desc]) => `<article class="card"><h3>${esc(title)}</h3><p>${esc(desc)}</p></article>`).join('');
const chips = items => `<div class="chips">${items.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>`;
for (const lang of ['zh', 'en']) {
  const C = existing[lang], X = extra[lang], en = lang === 'en';
  const url = route => `${en ? '/en' : ''}/${route ? route + '/' : ''}`;
  const t = (zh,eng) => en ? eng : zh;
  const button = (route,label) => `<a class="button" href="${url(route)}">${esc(label)}</a>`;
  const section = (title,body,cls='') => `<section class="section ${cls}"><div class="container"><h2 class="section-heading">${esc(title)}</h2>${body}</div></section>`;
  const hero = (eyebrow,title,desc) => `<section class="hero"><div class="container"><p class="eyebrow">${esc(eyebrow)}</p><h1>${esc(title)}</h1><p class="lead">${esc(desc)}</p></div></section>`;
  const productCards = C.products.items.map((p,i)=>`<article class="card"><img class="card-image" src="/img/${esc(C.business[i].image)}.jpg" alt="${esc(C.business[i].imageAlt)}" width="1200" height="675" loading="lazy"><p class="eyebrow">${esc(p.tag)}</p><h3>${esc(p.title)}</h3><p><strong>${esc(p.summary)}</strong></p><p>${esc(p.description)}</p>${chips(p.modules)}</article>`).join('');
  const postCards = X.posts.map(p=>`<article class="card"><p class="eyebrow">${esc(p.category)}</p><h2><a href="${url('blog/'+p.slug)}">${esc(p.title)}</a></h2><p>${esc(p.summary)}</p><a href="${url('blog/'+p.slug)}">${t('阅读全文 →','Read article →')}</a></article>`).join('');
  const pages = {};
  pages[''] = { title:C.pageTitle, description:C.hero.description, body:hero('Sun-Shine.ai · '+t('顺晟智能','Intelligent growth'),C.hero.title,C.hero.description)+section(t('从理解到增长','From understanding to growth'),`<div class="actions">${button('products',t('探索产品','Explore products'))}${button('about',t('认识 SunShine','Meet SunShine'))}</div><video class="video-frame" controls muted playsinline preload="metadata" poster="/video/brand-video-poster.jpg" src="${esc(C.brandVideo.videoSrc)}"></video>`)+section(t('四大产品体系','Four product pillars'),`<div class="grid two">${productCards}</div>`,'soft')+section(t('走进 SunShine','Explore SunShine'),`<div class="grid three">${routes.map((r,i)=>`<a class="card" href="${url(r)}"><p class="eyebrow">0${i+1}</p><h2>${labels[lang][i]} →</h2></a>`).join('')}</div>`)};
  pages.about = {title:labels[lang][0],description:X.about.intro,body:hero('ABOUT SUNSHINE',labels[lang][0],X.about.intro)+section(t('公司简介','Company profile'),`<p class="lead">${esc(X.about.intro)}</p><div class="grid two">${cards([[t('公司使命','Our mission'),X.about.mission],[t('公司愿景','Our vision'),X.about.vision]])}</div>`)+section(t('组织架构','Organization'),`<p>${esc(X.about.orgNote)}</p><div class="org-root">Sun-Shine.ai</div><div class="grid four">${cards(X.about.org)}</div>`,'soft')+section(t('公司历史与发展路线','Company history & direction'),`<p>${esc(X.about.historyNote)}</p><ol class="timeline">${X.about.history.map(([title,desc])=>`<li><h3>${esc(title)}</h3><p>${esc(desc)}</p></li>`).join('')}</ol>`)};
  pages.products = {title:labels[lang][1],description:C.services.description,body:hero('PRODUCTS',t('让 AI 成为企业的能力','Make AI an enterprise capability'),C.services.description)+section(t('公司产品介绍','Our products'),`<div class="grid two">${productCards}</div>`)+[C.agents,C.operations,C.delivery].map(g=>section(g.title,`<p class="lead">${esc(g.description)}</p><div class="grid two">${cards(g.items.map(a=>[a.title,a.description]))}</div><p class="notice">${esc(g.demoNote)}</p>`,'soft')).join('')+section(t('合作方式','Engagement models'),`<div class="grid three">${cards(C.businessModel.items)}</div>`)+section(C.industries.label,chips(C.industries.items),'soft')};
  pages.cases = {title:labels[lang][2],description:C.caseStudies.description,body:hero('CASE STUDIES','JoyLink Wire Mesh Global Trade Agentic',C.caseStudies.description)+section(t('全球线材贸易与 Agent 协作','Global wire-mesh trade & Agent collaboration'),`<img class="feature-image" src="/img/joylink-wire-mesh-agentic.png" width="1672" height="941" alt="${esc(C.caseStudies.imageAlt)}"><div class="grid three">${cards(C.caseStudies.items)}</div><div class="actions">${button('contact',t('讨论类似项目','Discuss a similar project'))}</div>`)};
  pages.blog = {title:labels[lang][3],description:t('关于企业增长、数据与 Agent 的实践思考。','Practical perspectives on growth, data, and enterprise Agents.'),body:hero('INSIGHTS',t('博客与洞察','Blog & insights'),t('从业务问题出发，记录方法、判断与实践。','Methods, decisions, and practice, starting with real business questions.'))+section(t('最新文章','Articles'),`<div class="grid three">${postCards}</div>`)};
  pages.faq = {title:'FAQ',description:C.faq.title,body:hero('FAQ',t('常见问题','Frequently asked questions'),C.faq.title)+section(t('你可能想了解','What you may want to know'),C.faq.items.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')+`<div class="actions">${button('contact',t('还有问题？联系我们','More questions? Contact us'))}</div>`)};
  pages.contact = {title:labels[lang][5],description:C.contact.description,body:hero('CONTACT',C.contact.title,C.contact.description)+section(t('整理你的合作需求','Prepare your project brief'),`<p class="notice">${t('填写后可生成并复制需求说明，便于通过你已有的 SunShine 联系渠道分享。本页不会发送或收集表单信息。','Generate and copy a brief to share through your existing SunShine contact channel. This page does not send or collect form information.')}</p><form id="contact-form"><div class="form-grid"><label class="field">${esc(C.contact.company)}<input name="company" required autocomplete="organization" placeholder="${esc(C.contact.companyPlaceholder)}"></label><label class="field">${esc(C.contact.email)}<input name="email" type="email" required autocomplete="email" placeholder="name@company.com"></label></div><label class="field">${esc(C.contact.goal)}<textarea name="goal" rows="5" required placeholder="${esc(C.contact.goalPlaceholder)}"></textarea></label><button class="button" type="submit">${t('生成需求说明','Generate brief')}</button></form><div id="brief-panel" hidden><label class="field">${t('需求说明','Your brief')}<textarea id="brief-output" rows="9" readonly></textarea></label><button id="copy-brief" class="button" type="button">${t('复制需求','Copy brief')}</button></div><p id="form-note" role="status" aria-live="polite"></p>`)};
  pages.products.body = `<div class="about-hero-video"><video src="/video/sunshine-products-hero-10s.mp4" poster="/img/sunshine-growth.jpg" autoplay muted loop playsinline controls preload="metadata" aria-label="${t('SunShine 四大产品体系，10 秒展示视频','SunShine four product pillars, 10-second showcase')}"></video></div>` + pages.products.body;
  pages.cases.body = `<div class="about-hero-video"><video src="/video/sunshine-cases-hero-10s.mp4" poster="/img/joylink-wire-mesh-agentic.png" autoplay muted loop playsinline controls preload="metadata" aria-label="${t('JoyLink 全球线材贸易案例，10 秒展示视频','JoyLink global wire-mesh trade case study, 10-second showcase')}"></video></div>` + pages.cases.body;
  pages.about.body = `<div class="about-hero-video"><video src="/video/01_outbound.mp4" autoplay muted loop playsinline controls preload="metadata" aria-label="${t('SunShine 企业出海展示视频','SunShine global business showcase video')}"></video></div>` + pages.about.body;
  for (const p of X.posts) pages['blog/'+p.slug] = {title:p.title,description:p.summary,body:hero(p.category,p.title,p.summary)+`<article class="container article">${p.sections.map(([h,body])=>`<section><h2>${esc(h)}</h2><p>${esc(body)}</p></section>`).join('')}<div class="actions">${button('blog',t('返回博客','Back to blog'))}${button('contact',t('讨论你的项目','Discuss your project'))}</div></article>`};
  for (const [route,p] of Object.entries(pages)) {
    const other = `${en ? '' : '/en'}/${route ? route+'/' : ''}`;
    const nav = routes.map((r,i)=>`<a class="nav-link${route===r||route.startsWith(r+'/')?' active':''}" ${route===r||route.startsWith(r+'/')?'aria-current="page"':''} href="${url(r)}">${labels[lang][i]}</a>`).join('');
    const html = `<!doctype html><html lang="${en?'en':'zh-CN'}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(p.title)} | Sun-Shine.ai</title><meta name="description" content="${esc(p.description)}"><link rel="icon" href="/sun-shine-logo.png"><link rel="stylesheet" href="/site.css"><link rel="alternate" hreflang="${en?'zh-CN':'en'}" href="${other}"><script src="/site.js" defer></script></head><body><a class="skip-link" href="#main">${t('跳到正文','Skip to content')}</a><header class="site-header"><div class="container header-inner"><a class="brand" href="${url('')}" aria-label="SunShine ${t('首页','home')}"><img src="/sun-shine-logo.png" width="40" height="40" alt="">sunshine<span>.ai</span></a><nav class="site-nav" id="site-nav" aria-label="${t('主导航','Main navigation')}">${nav}</nav><div class="header-actions"><a class="language-toggle" href="${other}" lang="${en?'zh-CN':'en'}" data-language="${en?'zh':'en'}">${en?'中文':'EN'}</a><button class="menu-toggle" aria-expanded="false" aria-controls="site-nav" type="button">${t('菜单','Menu')}</button></div></div></header><main id="main" class="site-main">${p.body}</main><footer class="site-footer"><div class="container footer-inner"><p>© 2026 Sun-Shine.ai · ${t('顺晟智能','From understanding to growth')}</p><div class="page-links">${nav}</div></div></footer></body></html>`;
    const dest = path.join(out,en?'en':'',route,'index.html');
    fs.mkdirSync(path.dirname(dest),{recursive:true}); fs.writeFileSync(dest,html);
  }
}
console.log('Built bilingual homepage, six standalone pages, and six blog article pages.');
